version: '3'
volumes:
  db-data:
services:
  db:
    image: mariadb:10.3.22
    ports: 
    - "3306:3306"
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: seletivo
        MYSQL_USER: seletivo
        MYSQL_PASSWORD: seletivo     
    volumes:
    - db-data:/var/lib/mysql    
  web:   
    build: 
      context: '.'
      dockerfile: ./.docker/Dockerfile
      args: 
        uid: ${UID}
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
    - "8000:80"
    volumes:    
    - ./:/var/www/html
    - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    links:
    - db