version: '3'
volumes:
  db-data:
services:
  db:
    image: mariadb:10.3.22
    ports: 
    - "3306:3306"
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: seletivo
        MYSQL_USER: seletivo
        MYSQL_PASSWORD: seletivo     
    volumes:
    - db-data:/var/lib/mysql    
  web:   
    image: tiagoheineckifc/laravel:php-7.4
    ports:
    - "8000:80"
    volumes:    
    - ./:/var/www/html
    - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    links:
    - db